In [2]:
import numpy as np

### Fancy indexing
Selecting multiple elements

In [16]:
arr = np.arange(1,7)
indices = [1,3,4] # Don't do it directly.
arr[indices]

array([2, 4, 5])

### Exercises

1. Create a 3×3 array filled with random numbers and print its shape.

In [10]:
rnd = np.random.default_rng()
arr2 = rnd.integers(1,10,size=(3,3))
arr2.shape

(3, 3)

2. Convert an array of floats [1.1, 2.2, 3.3] into integers.

In [15]:
arr3 = np.array([1.1, 2.2, 3.3])
arr3 = np.astype(arr3,"int32")
arr3

array([1, 2, 3], dtype=int32)

3. Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].

In [20]:
# we will use arr
ix = [1,3,5]
print(arr[ix])

# boolean masking
print(arr[arr % 2 == 0])

[2 4 6]
[2 4 6]


3. Reshape a 1D array of size 9 into a 3×3 matrix.

In [26]:
arr4 = rnd.integers(1, 10, 9)
arr4.reshape((3,3))

array([[8, 9, 5],
       [5, 9, 5],
       [6, 8, 9]])

4. Use boolean masking to filter numbers greater than 50 in an array.

In [29]:
arr5 = np.arange(40, 100, 10)
arr5[arr5 > 50]

array([60, 70, 80, 90])

In [30]:
a3 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

               [[13, 14, 15, 16],
                [17, 18, 19, 20],
                [21, 22, 23, 24],],

               [[25, 26, 27, 28],
                [29, 30, 31, 32],
                [33, 34, 35, 36]]])
a3[:,:,0] = 1
print(a3)

[[[ 1  2  3  4]
  [ 1  6  7  8]
  [ 1 10 11 12]]

 [[ 1 14 15 16]
  [ 1 18 19 20]
  [ 1 22 23 24]]

 [[ 1 26 27 28]
  [ 1 30 31 32]
  [ 1 34 35 36]]]
